### ISSUE TITLE
Image upload does not work!

### ISSUE THREAD

**Issue by ourren** [anruence/yii2-editor.md#1]
Hi, 

Image upload seems did not work at present?

Best,

Toby

**Comment by anruence** [comment]
you need config the imageUploadURL. : ) 
http://www.anruence.com/blog/1.html

**Comment by itswuanran** [comment]
you need config the imageUploadURL. : ) 
http://www.anruence.com/blog/1.html

**Comment by ourren** [comment]
I have tried twice, but it also did not work.

Currently, this [repo](https://github.com/yiier/yii2-editor.md) works.

**Comment by anruence** [comment]
nice, he make this better.

**Comment by itswuanran** [comment]
nice, he makes this better.
